
const safe = (value) => String(value || 'Not available').replace(/[^ -~]/g, '');

export async function downloadPredictionReport({ result, breed, image }) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const width = 210;
  const margin = 16;
  let y = 18;

  const header = () => {
    doc.setFillColor(7, 121, 93);
    doc.rect(0, 0, width, 26, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.text('CattleAI', margin, 12);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('INDIAN CATTLE BREED RECOGNITION SYSTEM', margin, 19);
    y = 36;
  };
  const ensureSpace = (height) => { if (y + height > 275) { doc.addPage(); header(); } };
  const section = (title) => {
    ensureSpace(14);
    doc.setFillColor(223, 246, 233);
    doc.roundedRect(margin, y, width - margin * 2, 9, 2, 2, 'F');
    doc.setTextColor(7, 91, 73); doc.setFont('helvetica', 'bold'); doc.setFontSize(10);
    doc.text(title.toUpperCase(), margin + 4, y + 5.9); y += 14;
  };
  const row = (label, value) => {
    const content = doc.splitTextToSize(safe(value), 113);
    const height = Math.max(8, content.length * 4.8 + 3);
    ensureSpace(height + 1);
    doc.setDrawColor(223, 233, 229); doc.line(margin, y + height, width - margin, y + height);
    doc.setFont('helvetica', 'bold'); doc.setTextColor(54, 82, 76); doc.setFontSize(8.5); doc.text(label, margin + 3, y + 5);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17, 41, 36); doc.text(content, 74, y + 5);
    y += height;
  };

  header();
  doc.setTextColor(16, 41, 39); doc.setFont('helvetica', 'bold'); doc.setFontSize(21); doc.text('Prediction Report', margin, y); y += 8;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(91, 116, 109); doc.text(`Generated ${new Date().toLocaleString()}`, margin, y); y += 10;

  if (image?.startsWith('data:image')) {
    try { doc.addImage(image, image.startsWith('data:image/png') ? 'PNG' : 'JPEG', margin, y, 57, 43, undefined, 'FAST'); } catch { /* The report remains valid without an image. */ }
  }
  doc.setFont('helvetica', 'bold'); doc.setTextColor(16, 41, 39); doc.setFontSize(17); doc.text(safe(result.predicted_breed), image?.startsWith('data:image') ? 82 : margin, y + 12);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(7, 121, 93); doc.text(`Confidence score: ${((result.confidence || 0) * 100).toFixed(1)}%`, image?.startsWith('data:image') ? 82 : margin, y + 20);
  doc.setTextColor(91, 116, 109); doc.setFontSize(8.5); doc.text(`Prediction time: ${result.inference_time_ms ? `${result.inference_time_ms} ms` : 'Not reported'}`, image?.startsWith('data:image') ? 82 : margin, y + 27);
  y += image?.startsWith('data:image') ? 53 : 39;

  section('Breed information');
  row('Scientific name', breed.scientificName); row('Category', breed.category); row('Breed type', breed.type); row('Origin state(s)', breed.originStates); row('Native region', breed.nativeRegion); row('Average milk yield', breed.milkYield); row('Average weight', breed.weight); row('Primary uses', breed.primaryUses);
  section('Characteristics');
  row('Coat colour', breed.coatColour); row('Horn shape', breed.hornShape); row('Body characteristics', breed.bodyCharacteristics); row('Climate adaptability', breed.climateAdaptability); row('Temperament', breed.temperament); row('Disease resistance', breed.diseaseResistance); row('Life span', breed.lifeSpan); row('Suitable farming conditions', breed.suitableFarmingConditions);
  section('Interesting fact'); row('Did you know?', breed.interestingFacts); row('Conservation status', breed.conservationStatus);

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) { doc.setPage(page); doc.setDrawColor(223, 233, 229); doc.line(margin, 287, width - margin, 287); doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(91, 116, 109); doc.text('Generated by Indian Cattle Breed Recognition System', margin, 292); doc.text(`Page ${page} of ${pages}`, width - margin, 292, { align: 'right' }); }
  doc.save(`${safe(result.predicted_breed).replace(/\s+/g, '-').toLowerCase()}-prediction-report.pdf`);
}
